### ISSUE TITLE
希望能增加日本斗鱼的独轮车支持

### ISSUE THREAD

**Issue by iPixelOldC** [zhenshiluosuo/Storyteller-AutoBarrageForDouyuTV#3]
网站：www.mildom.com
谢谢，大佬

**Comment by zhenshiluosuo** [comment]
这个输入事件有些特殊，需要研究一下

**Comment by iPixelOldC** [comment]
嗯嗯，谢谢大佬O(∩_∩)O&nbsp;





------------------ 原始邮件 ------------------
发件人: ShiningMage <notifications@github.com&gt;
发送时间: 2020年10月22日 02:00
收件人: zhenshiluosuo/Storyteller-AutoBarrageForDouyuTV <Storyteller-AutoBarrageForDouyuTV@noreply.github.com&gt;
抄送: iPixelOldC <ipixeloldc@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zhenshiluosuo/Storyteller-AutoBarrageForDouyuTV] 希望能增加日本斗鱼的独轮车支持 (#3)





 
这个输入事件有些特殊，需要研究一下

**Comment by zhenshiluosuo** [comment]
从NGA问到了实现方法，已经支持了，使用出现问题跟我说哈

**Comment by iPixelOldC** [comment]
我也看到了，谢谢大佬





------------------ 原始邮件 ------------------
发件人: ShiningMage <notifications@github.com&gt;
发送时间: 2020年10月25日 03:42
收件人: zhenshiluosuo/Storyteller-AutoBarrageForDouyuTV <Storyteller-AutoBarrageForDouyuTV@noreply.github.com&gt;
抄送: iPixelOldC <ipixeloldc@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zhenshiluosuo/Storyteller-AutoBarrageForDouyuTV] 希望能增加日本斗鱼的独轮车支持 (#3)






从NGA问到了实现方法，已经支持了，使用出现问题跟我说哈
